export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASK_DETAIL = 'FETCH_TASK_DETAIL';
export const FETCH_TASKS_BY_CATEGORY = 'FETCH_TASKS_BY_CATEGORY';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';

export const TASKS_ERROR = 'TASKS_ERROR';
export const SET_LOADING = 'SET_LOADING';
export const SET_IS_SUBMITTING_ADD = 'SET_IS_SUBMITTING_ADD';
export const SET_IS_SUBMITTING_EDIT = 'SET_IS_SUBMITTING_EDIT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
