import dateTimeFormat from './DateTimeFormat';

const data = [
  {
    id: '1',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC', 'Frontend'],
    category: 'Blocker',
    status: 'open',
  },
  {
    id: '2',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'open',
  },
  {
    id: '3',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    status: 'open',
    category: 'Work',
  },
  {
    id: '4',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'open',
  },
  {
    id: '5',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'open',
  },
  {
    id: '6',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'open',
  },
  {
    id: '7',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'open',
  },
  {
    id: '8',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'open',
  },
  {
    id: '9',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'inProgress',
  },
  {
    id: '10',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'inProgress',
  },
  {
    id: '11',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'inProgress',
  },
  {
    id: '12',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    category: 'Work',
    tags: ['Backend', 'Devops', 'BA/QC'],
    status: 'inProgress',
  },
  {
    id: '13',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    category: 'Work',
    tags: ['Backend', 'Devops', 'BA/QC'],
    status: 'completed',
  },
  {
    id: '14',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'completed',
  },
  {
    id: '15',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'completed',
  },
  {
    id: '16',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Test',
    status: 'completed',
  },
  {
    id: '17',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'completed',
  },
  {
    id: '18',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Blocker',
    status: 'completed',
  },
  {
    id: '19',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Blocker',
    status: 'completed',
  },
  {
    id: '20',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'archived',
  },
  {
    id: '21',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Document',
    status: 'archived',
  },
  {
    id: '22',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'archived',
  },
  {
    id: '23',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'archived',
  },
  {
    id: '24',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Work',
    status: 'archived',
  },
  {
    id: '25',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'archived',
  },
  {
    id: '26',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'inProgress',
  },
  {
    id: '27',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'inProgress',
  },
  {
    id: '28',
    task: 'Task Added Edited',
    createdAt: '1/8/2024',
    description:
      'Task Added For Whole Internal Team development. We need specify requirement and due date for finishing and archiving on time. Please discuss with manager onshore after received task. Thanks',
    dueDate: '1/8/2024',
    tags: ['Backend', 'Devops', 'BA/QC'],
    category: 'Workshop',
    status: 'inProgress',
  },
];
export default data;
